import Head from "next/head";
import Image from "next/image";
import React, { useState, useEffect } from "react";
import styles from "../styles/Home.module.css";
import Router, { useRouter } from "next/router";

import "bootstrap/dist/css/bootstrap.min.css";
// import bootstrap from 'bootstrap';
import MoviesData from "./MoviesData";

export default function Home() {
  const [searchval, setSearchval] = useState("");
  const [movieslist, setMoviesList] = useState([]);
  const router = useRouter();

  const searchMovies = async (e) => {
    e.preventDefault();
    // console.log("submitting");

    const url = `http://www.omdbapi.com/?apikey=2f079760&s=${searchval}`;

    const res = await fetch(url);
    const data = await res.json();

    setMoviesList(data.Search);
    console.log(movieslist);
  };

  // const openInfo = async (id) => {
  //   const url = `http://www.omdbapi.com/?apikey=2f079760&i=${id}&pllot=full`;

  //   const res = await fetch(url);
  //   const data = await res.json();
    
  //   router.push(`Movieinfo/${id}`);
  // };


  const openInfo = (MovieId) => {
    router.push(`/${MovieId}`);
  };

  return (
    <div className="container">
      <Head>
        <title>React Movie Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
        <h3 className="title">Movie Search Engine</h3>
        <form className="form" onSubmit={searchMovies}>
          <div className="container">
            <label className="label">Movie Name : </label>
            <input
              type={"text"}
              className="input"
              name="text"
              value={searchval}
              onChange={(e) => setSearchval(e.target.value)}
            ></input>
            <button
              type="submit"
              className="button SearchBtn"
              onClick={searchMovies}
            >
              Search
            </button>
          </div>
        </form>

        <div className="card-list">
          <MoviesData
            movieslist={movieslist}
            // openInfo = {openInfo}
          />
        </div>
      </main>
    </div>
  );
}
